version: "4"

services:
  db:
    image: postgres
    container_name: flask-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=db
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    depends_on:
      db:
        condition: service_healthy
    container_name: flask-api
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:changeme@db:5432/db}
    ports:
      - "80:80"
    networks:
      - postgres
    restart: always

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
